# Generated by Django 5.1.2 on 2024-11-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blogpost_recipes_recommendrecipe_delete_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='blog/'),
        ),
    ]
