# Generated by Django 5.1.3 on 2024-11-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendrecipe',
            name='cook_time',
            field=models.PositiveIntegerField(default=0, help_text='Cook time in minutes'),
            preserve_default=False,
        ),
    ]
