# Generated by Django 5.1.3 on 2024-11-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_recommendrecipe_cook_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='cook_time',
            field=models.PositiveIntegerField(default=0, help_text='Cook time in minutes'),
        ),
        migrations.AlterField(
            model_name='recommendrecipe',
            name='cook_time',
            field=models.PositiveIntegerField(default=0, help_text='Cook time in minutes'),
        ),
    ]
